### ISSUE TITLE
data type error

### ISSUE THREAD

**Issue by arvinhuang-crypto** [WeBankPartners/go-common-lib#3]
github.com/!we!bank!partners/go-common-lib@v1.0.24/token/wecube.go:88:56: cannot use rsaKey (type string) as type []byte in argument to "github.com/WeBankPartners/go-common-lib/cipher".RSAEncryptByPrivate

func (c *CoreToken) requestCoreToken(rsaKey string) error {
	encryptBytes, err := cipher.RSAEncryptByPrivate([]byte(fmt.Sprintf("%s:%s", c.SubSystemCode, requestCoreNonce)), rsaKey)

func RSAEncryptByPrivate(sourceData, privateKeyContent []byte) ([]byte, error) {
	privateKeyString := string(privateKeyContent)

version: v1.0.24
data type error

**Comment by duee** [comment]
这么处理？
